version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/compute-js" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
