# Netlify configuration
# TODO: Replace this placeholder with content from netlify.toml from netlify branch

[build]
  command = "./scripts/netlify-build.sh"
  publish = "site"

# TODO: Add other netlify-specific configurations from the actual netlify.toml file

[build.environment]
  PYTHON_VERSION = "3.9"