---
name: Promote Staging to Production

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      collection_name:
        description: 'Collection to promote (default: staging)'
        required: false
        default: 'staging'
        type: string
      confirm:
        description: 'Type "PROMOTE" to confirm promotion to production'
        required: true
        type: string

jobs:
  promote:
    name: Promote to Production
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rocky-linux/docs-builder:latest
    environment: production
    steps:
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "PROMOTE" ]; then
            echo "❌ Confirmation failed. You must type 'PROMOTE' to proceed."
            exit 1
          fi
          echo "✅ Confirmation validated"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ./compute-js

      - name: Check collection exists
        run: |
          echo "🔍 Checking if collection '${{ github.event.inputs.collection_name }}' exists..."
          npx @fastly/compute-js-static-publish collections list | grep -q "${{ github.event.inputs.collection_name }}" || {
            echo "❌ Collection '${{ github.event.inputs.collection_name }}' not found"
            exit 1
          }
          echo "✅ Collection '${{ github.event.inputs.collection_name }}' found"
        working-directory: ./compute-js
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}

      - name: Promote to Production
        run: |
          echo "🚀 Promoting '${{ github.event.inputs.collection_name }}' to production..."
          npx @fastly/compute-js-static-publish collections promote \
            --collection-name=${{ github.event.inputs.collection_name }} \
            --to=default \
            --expires-never
        working-directory: ./compute-js
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}

      - name: Output success
        run: |
          echo "🎉 Successfully promoted '${{ github.event.inputs.collection_name }}' to production!"
          echo "📄 Collection: default (production)"
          echo "⏰ Expires: never"